#!/bin/bash
if [[ ${DEVAUDIT_TRACE+x} ]]
then 
	mono --trace=$DEVAUDIT_TRACE ./DevAudit.CommandLine/bin/Debug/devaudit.exe "$@"
else
	mono --debug ./DevAudit.CommandLine/bin/Debug/devaudit.exe "$@"
fi
